name: CI

on: [push, pull_request]

jobs:
  spotless:
    name: Spotless

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Spotless
        run: ./gradlew spotlessCheck

  tests:
    name: Tests

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 8, 11, 16 ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}

      - name: Display version
        run: ./gradlew --version

      - name: Build artifacts
        run: ./gradlew assemble

      - name: Start stripe-mock
        run: docker run -d -p 12111-12112:12111-12112 stripemock/stripe-mock && sleep 5

      - name: Run test suite
        run: ./gradlew check

      - name: Send code coverage report to coveralls.io
        run: ./gradlew jacocoTestReport coveralls
        env:
          CI_NAME: github-actions
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
